# -*- coding: utf-8 -*-
"""fake_news_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laxDz35DkuIsShIOEa-ap1lewMR1_LC6
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your specific dataset
# If you are in Colab, upload the file first then use the path below
df = pd.read_csv('FA-KES-Dataset.csv', encoding='latin1') # 'latin1' often helps with Excel-based CSVs

# Basic Cleaning
# We use 'article_content' as our main text and 'labels' as our target
df = df.dropna(subset=['article_content', 'labels'])

# 1. Dataset Summary
print(f"Total Articles: {len(df)}")
print(f"Columns in your file: {df.columns.tolist()}")

# 2. Label Distribution
print("\n--- Label Distribution ---")
print(df['labels'].value_counts())

# 3. Visualization
sns.countplot(x='labels', data=df)
plt.title('Fake vs Real Distribution (FA-KES Dataset)')
plt.show()

# 4. Show 5 Sample Entries
display(df[['article_title', 'labels']].head())

from transformers import BertTokenizer
from sklearn.model_selection import train_test_split
import torch

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Map your columns
sentences = df.article_content.values
labels = df.labels.values

# Tokenization
encoded_dict = tokenizer(
    list(sentences),
    add_special_tokens=True,
    max_length=256, # Increased length for full articles
    padding='max_length',
    truncation=True,
    return_attention_mask=True,
    return_tensors='pt'
)

# Split into Train (80%) and Validation (20%)
train_idx, val_idx = train_test_split(range(len(labels)), test_size=0.2, random_state=42)

# Create Tensors
train_inputs = encoded_dict['input_ids'][train_idx]
train_masks = encoded_dict['attention_mask'][train_idx]
train_labels = torch.tensor(labels[train_idx])

val_inputs = encoded_dict['input_ids'][val_idx]
val_masks = encoded_dict['attention_mask'][val_idx]
val_labels = torch.tensor(labels[val_idx])

print(f"Preparation complete. Training samples: {len(train_inputs)}")

from transformers import BertForSequenceClassification, Trainer, TrainingArguments

# Load Model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# PyTorch Dataset Wrapper
class FakeNewsDataset(torch.utils.data.Dataset):
    def __init__(self, ids, masks, labels):
        self.ids = ids
        self.masks = masks
        self.labels = labels
    def __getitem__(self, idx):
        return {'input_ids': self.ids[idx], 'attention_mask': self.masks[idx], 'labels': self.labels[idx]}
    def __len__(self):
        return len(self.labels)

train_dataset = FakeNewsDataset(train_inputs, train_masks, train_labels)
val_dataset = FakeNewsDataset(val_inputs, val_masks, val_labels)

# Training Config
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=0.1,
    per_device_train_batch_size=8,
    # evaluation_strategy="epoch", # Removed due to TypeError in current library version
    # save_strategy="epoch", # Removed alongside evaluation_strategy for compatibility
    logging_dir='./logs',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

# Start Fine-tuning
trainer.train()

from sklearn.metrics import classification_report, confusion_matrix

# Get Predictions
preds_output = trainer.predict(val_dataset)
predictions = preds_output.predictions.argmax(-1)

# Report
print("Classification Report for FA-KES Dataset:")
print(classification_report(val_labels, predictions))

# Confusion Matrix
cm = confusion_matrix(val_labels, predictions)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Create a dataframe for the validation set to compare
val_df = df.iloc[val_idx].copy()
val_df['predicted_label'] = predictions

# Filter for incorrect predictions
errors = val_df[val_df['labels'] != val_df['predicted_label']]

print(f"Total Errors: {len(errors)}")
print("\n--- Top 5 Misclassified Samples ---")
display(errors[['article_title', 'labels', 'predicted_label']].head(5))

import gradio as gr

def fakes_checker(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=256)
    # Move model to CPU for the demo
    model.to("cpu")
    outputs = model(**inputs)
    prediction = torch.argmax(outputs.logits, dim=-1).item()
    return "FAKE/UNRELIABLE" if prediction == 1 else "REAL/RELIABLE"

demo = gr.Interface(fn=fakes_checker, inputs="text", outputs="label", title="FA-KES News Detector")
demo.launch(share=True)

"""After uploading, the file will be available in the Colab environment. You can then access it by its filename, for example, `df = pd.read_csv('your_uploaded_filename.csv')`."""